### ISSUE TITLE
BssomSerializer.Deserialize反序列化对象时，如果属性的set为private，则会出错

### ISSUE THREAD

**Issue by limocute** [1996v/Bssom.Net#2]
BssomSerializer.Deserialize反序列化对象时，如果对象某个属性的set不为public，则会出错
例如
```
public class TestA
{
  public int P1 { get; set; }
  public bool P2 { get; private set; }
  public bool P3 { get; internal set; }
}
```
应当检查对象属性是否可写入

**Comment by 1996v** [comment]
默认只对公开的可读和可写的元素进行序列化和反序列化，在1.0.2版本中增加了MapCodeGenResolverAllowPrivate和CompositedResolverAllowPrivate ，现在，Bssom支持私有元素的序列化和反序列化
